[project]
name = "githubrecapped"
version = "0.1.0"
description = "summary of your github profile!"
readme = "README.md"
authors = [
    { name = "dorkishguy", email = "ameenstrtshackclub@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
githubrecapped = "githubrecapped:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
